name: 🐛 Bug Report
description: File a report to help us improve Project David AI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you did!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the tool are you using?
      options:
        - v1.2.0 (Latest)
        - v1.1.0
        - v1.0.0
        - Beta / Development branch
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
